version: '2'
services:
  app:
    restart: 'no'
    image: ${DOCKER_BASE_URL}/${DOCKER_BASE_IMAGE}:${DOCKER_BASE_TAG}-dev
    container_name: ${COMPOSE_PROJECT_NAME}
    depends_on:
      - data
    env_file:
      - .env
    environment:
      - APACHE_LOG_DIR=/var/www/logs
    volumes:
      - ${APP_SSH_DIR}:/home/ssh-labor/.ssh
      - ${APP_WORKING_DIR}:/var/www/html
      - ${APP_LOG_DIR}:/var/www/logs
      - ${APP_OPT_DIR}/bootstrap-project.sh:/opt/bootstrap-project.sh
      - ${APP_OPT_DIR}/directories.sh:/opt/directories.sh
      - ${APP_OPT_DIR}/bootstrap-dev.sh:/opt/bootstrap-dev.sh
      - ${APP_OPT_DIR}/permissions.sh:/opt/permissions.sh
    volumes_from:
      - data
    networks:
      - labor_infrastructure
  data:
    restart: 'no'
    container_name: ${COMPOSE_PROJECT_NAME}-data
    image: ubuntu
    volumes:
      - ${APP_DATA_DIR}:/var/www/html_data
    networks:
      - labor_infrastructure

networks:
  labor_infrastructure:
    external: true